import dotenv from "dotenv";
dotenv.config();

console.log(process.env);
const config = {
	baseUrl: process.env.REACT_APP_BASE_URL + "/api",
	token: "/token",
	doctor: "/doctor",
	patient: "/patient",
	admin: "/admin",
	login: "/login",
	getSpecialization: "/getSpecialization",
	getDoctors: "/getDoctors",
	signup: "/signup",
	remaining_appointment: "/remaining_appointment",
	getPatientCases: "/getPatientCases",
	getPatientAppointments: "/getPatientAppointments",
	newCase: "/newCase",
	newAppointment: "/newAppointment",
	schedule: "/schedule",
	appointment: "/appointment",
	allappointments: "/allappointments",
	setAvailability: "/setAvailability",
	doctor_details: "/doctor_details",
	meeting: "/newmeeting",
	video_token: "/video/token",
	add_doctor: "/add_doctor",
	verify: "/verify",
	DOCTOR: "doctor",
	PATIENT: "patient",
	ADMIN: "admin",
	profilePicUpload: "/profilePicUpload",
	getScheduledAppointments: "/getScheduledAppointments",
	getProfilePic: "/getProfilePic",
	getDoctorAppointments: "/getDoctorAppointments",
	addUserDetails: "/addUserDetails",
	changePassword: "/changePassword",
	getDoctorAvailability: "/getDoctorAvailability",
	verifyPhone: "/verifyPhone",
	getDoctorAppointmentDuration: "/getDoctorAppointmentDuration",
	setDoctorAppointmentDuration: "/setDoctorAppointmentDuration",
	forgotPassword: "/forgotPassword",
	getDoctorProfilePics: "/getDoctorProfilePics",
	getAllPatientAppointments: "/getAllPatientAppointments",
	cancelAppointment: "/cancelAppointment",
	rescheduleAppointment: "/rescheduleAppointment",
	verifyEmail: "/verifyEmail",
	updateEmail: "/updateEmail",
	getDoctorSpecialization: "/getDoctorSpecialization",
	addSpecialization: "/addSpecialization",
	removeDoctorSpecialization: "/removeDoctorSpecialization",
	removeDoctorQualification: "/removeDoctorQualification",
	addQualification: "/addQualification",
	getDoctorQualification: "/getDoctorQualification",
	getQualification: "/getQualification",
	getDoctorDaySlots: "/getDoctorDaySlots",
};
export default config;
