import dotenv from "dotenv";
dotenv.config();

console.log(process.env);
const config = {
	baseUrl: process.env.REACT_APP_BASE_URL,
	token: "/api/token",
	doctor: "/api/doctor",
	patient: "/api/patient",
	admin: "/api/admin",
	login: "/api/login",
	getSpecialization: "/api/getSpecialization",
	getDoctors: "/api/getDoctors",
	signup: "/api/signup",
	remaining_appointment: "/remaining_appointment",
	getPatientCases: "/api/getPatientCases",
	getPatientAppointments: "/api/getPatientAppointments",
	newCase: "/api/newCase",
	newAppointment: "/api/newAppointment",
	schedule: "/schedule",
	appointment: "/appointment",
	allappointments: "/allappointments",
	setAvailability: "/api/setAvailability",
	doctor_details: "/doctor_details",
	meeting: "/newmeeting",
	video_token: "/api/video/token",
	add_doctor: "/add_doctor",
	verify: "/verify",
	DOCTOR: "doctor",
	PATIENT: "patient",
	ADMIN: "admin",
	profilePicUpload: "/api/profilePicUpload",
	getScheduledAppointments: "/api/getScheduledAppointments",
	getProfilePic: "/api/getProfilePic",
	getDoctorAppointments: "/api/getDoctorAppointments",
	addUserDetails: "/api/addUserDetails",
	changePassword: "/api/changePassword",
	getDoctorAvailability: "/api/getDoctorAvailability",
	verifyPhone: "/api/verifyPhone",
	getDoctorAppointmentDuration: "/api/getDoctorAppointmentDuration",
	setDoctorAppointmentDuration: "/api/setDoctorAppointmentDuration",
	forgotPassword: "/api/forgotPassword",
	getDoctorProfilePics: "/api/getDoctorProfilePics",
	getAllPatientAppointments: "/api/getAllPatientAppointments",
	cancelAppointment: "/api/cancelAppointment",
	rescheduleAppointment: "/api/rescheduleAppointment",
	verifyEmail: "/api/verifyEmail",
	updateEmail: "/api/updateEmail",
	getDoctorSpecialization: "/api/getDoctorSpecialization",
	addSpecialization: "/api/addSpecialization",
	removeDoctorSpecialization: "/api/removeDoctorSpecialization",
};
export default config;
